// Command bootup-keyring-source writes ignored Go source for compile-time
// trust material.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"

	"github.com/dotwaffle/bootup/verify"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "bootup-keyring-source: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	flags := flag.NewFlagSet("bootup-keyring-source", flag.ContinueOnError)
	flags.SetOutput(os.Stderr)
	outputPath := flags.String("o", "internal/trustmaterial/debian_archive_keyring_generated.go", "output Go source path")
	if err := flags.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}
	if flags.NArg() != 1 {
		return errors.New("usage: bootup-keyring-source -o <output.go> <keyring.gpg>")
	}

	keyring, err := os.ReadFile(flags.Arg(0))
	if err != nil {
		return fmt.Errorf("read keyring: %w", err)
	}
	if _, err := verify.ReadKeyring(bytes.NewReader(keyring)); err != nil {
		return fmt.Errorf("validate keyring: %w", err)
	}
	source := formatSource(keyring)
	if err := os.WriteFile(*outputPath, source, 0o644); err != nil {
		return fmt.Errorf("write Go source: %w", err)
	}
	return nil
}

func formatSource(data []byte) []byte {
	out := []byte("// Code generated by bootup-keyring-source; DO NOT EDIT.\n\npackage trustmaterial\n\nfunc init() {\n\tdebianArchiveKeyring = []byte{\n")
	for index, value := range data {
		if index%12 == 0 {
			out = append(out, '\t')
		}
		out = fmt.Appendf(out, "0x%02x, ", value)
		if index%12 == 11 {
			out = append(out, '\n')
		}
	}
	if len(data)%12 != 0 {
		out = append(out, '\n')
	}
	out = append(out, "\t}\n}\n"...)
	return out
}
