#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "usage: $0 /path/to/kernel.config" >&2
	exit 2
fi

config="$1"
if [[ ! -r "${config}" ]]; then
	echo "kernel config is not readable: ${config}" >&2
	exit 2
fi

required_y=(
	CONFIG_KERNEL_ZSTD
	CONFIG_CMDLINE_BOOL
	CONFIG_64BIT
	CONFIG_BINFMT_ELF
	CONFIG_BLOCK
	CONFIG_BLK_DEV_INITRD
	CONFIG_DEVTMPFS
	CONFIG_DEVTMPFS_MOUNT
	CONFIG_EPOLL
	CONFIG_FUTEX
	CONFIG_PRINTK
	CONFIG_DEBUG_KERNEL
	CONFIG_PROC_FS
	CONFIG_KALLSYMS
	CONFIG_KALLSYMS_ALL
	CONFIG_PROC_KCORE
	CONFIG_SYSFS
	CONFIG_TMPFS
	CONFIG_TTY
	CONFIG_CRYPTO
	CONFIG_CRYPTO_SHA256
	CONFIG_KEXEC
	CONFIG_KEXEC_FILE
	CONFIG_RELOCATABLE
	CONFIG_SERIAL_8250
	CONFIG_SERIAL_8250_CONSOLE
	CONFIG_SERIAL_8250_PCI
	CONFIG_EARLY_PRINTK
	CONFIG_SYSFB
	CONFIG_FB
	CONFIG_FB_SIMPLE
	CONFIG_FB_EFI
	CONFIG_FB_VESA
	CONFIG_FRAMEBUFFER_CONSOLE
	CONFIG_VGA_CONSOLE
	CONFIG_FONT_8x16
	CONFIG_INPUT
	CONFIG_INPUT_KEYBOARD
	CONFIG_KEYBOARD_ATKBD
	CONFIG_SERIO
	CONFIG_SERIO_I8042
	CONFIG_SERIO_LIBPS2
	CONFIG_HID
	CONFIG_HID_GENERIC
	CONFIG_USB_HID
	CONFIG_EFI
	CONFIG_EFI_STUB
	CONFIG_EFI_PARTITION
	CONFIG_MSDOS_PARTITION
	CONFIG_NET
	CONFIG_NETDEVICES
	CONFIG_ETHERNET
	CONFIG_INET
	CONFIG_PACKET
	CONFIG_UNIX
	CONFIG_IPV6
	CONFIG_IP_PNP
	CONFIG_IP_PNP_DHCP
	CONFIG_PCI
	CONFIG_E1000
	CONFIG_VIRTIO
	CONFIG_VIRTIO_PCI
	CONFIG_VIRTIO_NET
	CONFIG_VIRTIO_BLK
	CONFIG_VIRTIO_CONSOLE
	CONFIG_HW_RANDOM
	CONFIG_HW_RANDOM_VIRTIO
	CONFIG_SCSI
	CONFIG_BLK_DEV_SD
	CONFIG_ATA
	CONFIG_SATA_AHCI
	CONFIG_ATA_PIIX
	CONFIG_ATA_GENERIC
	CONFIG_BLK_DEV_NVME
	CONFIG_USB
	CONFIG_USB_XHCI_HCD
	CONFIG_USB_XHCI_PCI
	CONFIG_USB_EHCI_HCD
	CONFIG_USB_OHCI_HCD
	CONFIG_USB_OHCI_HCD_PCI
	CONFIG_USB_UHCI_HCD
	CONFIG_USB_STORAGE
	CONFIG_EXT4_FS
	CONFIG_EXT4_USE_FOR_EXT2
	CONFIG_JBD2
	CONFIG_CRC16
	CONFIG_FAT_FS
	CONFIG_MSDOS_FS
	CONFIG_VFAT_FS
	CONFIG_NLS
	CONFIG_NLS_CODEPAGE_437
	CONFIG_NLS_ISO8859_1
	CONFIG_BLK_DEV_LOOP
	CONFIG_MISC_FILESYSTEMS
	CONFIG_SQUASHFS
	CONFIG_NET_9P
	CONFIG_NET_9P_VIRTIO
	CONFIG_9P_FS
	CONFIG_DMI_SYSFS
	CONFIG_RD_ZSTD
)

status=0
for symbol in "${required_y[@]}"; do
	if grep -qx "${symbol}=y" "${config}"; then
		continue
	fi
	if grep -qx "${symbol}=m" "${config}"; then
		echo "${symbol}=m, want ${symbol}=y for early boot" >&2
	elif grep -qx "# ${symbol} is not set" "${config}"; then
		echo "${symbol} is not set, want ${symbol}=y" >&2
	else
		echo "${symbol} is missing, want ${symbol}=y" >&2
	fi
	status=1
done

cmdline="$(sed -n 's/^CONFIG_CMDLINE="\(.*\)"$/\1/p' "${config}" | tail -n 1)"
required_cmdline_tokens=(
	"console=tty0"
	"console=ttyS0,115200n8"
	"earlyprintk=ttyS0,115200"
	"panic=30"
	"ip=::::::dhcp"
)
for token in "${required_cmdline_tokens[@]}"; do
	if [[ " ${cmdline} " == *" ${token} "* ]]; then
		continue
	fi
	echo "CONFIG_CMDLINE missing ${token}" >&2
	status=1
done

exit "${status}"
